query($limit: Int) {
  latestThemes: themeList(input: {
    limit: $limit
    sort: {
      createdAt: -1
    }
  }) {
    id
    createdBy {
      id
      username
      display
      avatarUrl
      smallAvatarUrl
    }
    rating {
      count
      value
    }
    title
    description
    content
    createdAt
    updatedAt
    version
    screenshots
    license
    variables {
      type
      label
      name
      value
    }
    stats {
      visits
      views
      avgRetention
      exitRate
      bounceRate
      totalTime
    }
  }
}
