query($terms: String!, $limit: Int, $skip: Int) {
  search(terms: $terms, limit: $limit, skip: $skip) {
    users {
      id
      username
      display
      avatarUrl
      smallAvatarUrl
      lastSeen
    }

    themes {
      id
      user {
        id
        username
        display
        avatarUrl
        smallAvatarUrl
      }
      title
      createdAt
      updatedAt
      screenshots
    }
  }
}
