query($token: String!) {
  verifyToken(token: $token) {
    id
    createdBy {
      id
      username
      display
      avatarUrl
      smallAvatarUrl
      lastSeenAt
      lastSeenReason
      createdAt
      updatedAt
      bio
      donationUrl
    }
    token
    expiresAt
    createdAt
    ip
    ua
  }
}
